language: node_js
install:
  - npm install codecov -g
  - npm ci
script:
  - npm test
after_success:
  - codecov
node_js:
  - lts/*
branches:
  only:
    - master
notifications:
  slack:
    if: type IN (pull_request) AND branch = master
    secure: S9BQbUclIojH7RGuOC32U/UIHP3buPI4lHAykEhQvpJ+50HihBb9neKDUsS4o9cR3CoBafNcGm24QkBBsNw0Zk7vUi9rxUmuJgSNlAkXh1/D0reQ4UsGDAp4lNHPgAmUEF2yQ9QR0uENVteXM5no9d3od+Rn22noApET1qXWMlIYqvKl6sZLz/U+z8ZHFTsCVLRaN+KdSrpv96rSBCiUkrmMqfAVhbR8J53bA/GB7cFPjZTlwuYLVklBP/HTkcFu13KBwwCLd8o5RcXoFUEd5G+y9OdgGxBpMNDRSziMKqtTyikEZ8BpgzA7x9+cThwvmOyJRwurXC3Cjdopul7JeUiIpi+LTq1G9fkWWAm0fP8+KqwShQrUqz8bq9xrD7RSp5Tx1pYtoUOo0to8CesXX55/iHuIu3IKjN7sQqJtA0gmD6qhEVA9CTuKTYkCAJ0pQDUqlNouj6yOcOnrsTCLM1ieWYUG10cf8mdSxd1zJpyUUgPUUv483kMnMdmrms04y+pcfKEmI/Z/9Yu1AQgHXnblWOITFMduf7ufoWbU8i2sc970L+xJ7ny263H2RS8ietqD2cQyMJ65R53Adf6x2VlCC5yw9vElBj5DHhXz6rrhOUInET6LppeFseyD/5sRDgUYrfSc92ShEkHvU92p16oEJp+NwTVtsREiJTGv0f8=
