language: node_js
install:
- npm install codecov -g
- npm ci
script:
- npm test
after_success:
- codecov
node_js:
- lts/*
- 13.13.0
notifications:
  slack:
    secure: ExbvhrCUcNzuhrUmmJLlm7Rcnsk5bnGBVJkSbwppDCPzGrBS0r+LHVoBMA/HJCMFy+fr3j8+f+n6+41cORPk1LH2lvbbHCGQG7KJ25Yi4NcGy0ed0E1hNJh2Iw/NEcNoZV7RcAkwH4PL+Y/2LY/xmijfnAq8QT2rFzW2rOVSxgdYR8MNlexMG6GmJmav1vKx5fO4PkHa6/8oIt4PrgXDzVqgGJxVL8blEWJnyK4evq6SCEWhC++Bv3tpHCvoK3lIv7hp4W4Kg5MZfILuBnsbMcmWjOPueSqYAG72FOlMV35x0HH8Knues02VpEhspBQv3sRijmEoxSHQi2GSXCF+PHQ4HoJc7Tn6EMvZ9feoXSbbFZYfr3i1gKkJIG/TCuQGaDuto1XyRfba2tUvuV4Bx7iuZeEtn922fOl/oli4wPyQ5QEP8lsHf4LNmMkTpJVvNzqhDRU78aToZXWTi6NA7W40KyG5F1jrJlFK4H1mSGRJFqgGyXOhJ+wuwe92tCkHk86K8bGY/c0Mab40dUUP/vnabXEojCTlpZ/XMvaOQxXMhoQV4ToDk+/AZvapvmRt4sbG2H6E5Mn1DYHE/cFPggOJVic7A/bMGtWrvoJCl5x+MyFc12ZA6tfmprNr0cTFRKKL1QGXIaEKqTesLiFVss7uWST3qd74mZTcLUvaScg=
