language: node_js
install:
  - npm install codecov -g
  - npm ci
script:
  - npm test
after_success:
  - codecov
node_js:
  - lts/*
branches:
  only:
    - master
notifications:
  slack:
    if: type = pull_request
    secure: pG+q3KmkLCdWQ2l7/rtal0Sq6umaeNRCD28MuY+ygz74QwKowo6qY71Hqf4GGjKD3oIWuob7sJxPrRJxh2YQvzL4VtAGh0mkRuw/0D0OooyVPZdXZT7XUNeM/nrskjSyqlhc618nepYIStLoBPbNHnGXvaxgQN2Gs6GR4+hzTsTdBbQjwLU/9zm0DfS+wTap12M7C0wunFz/sAwfRr94zD8mNA2J0f3TqJsk7Y9Lt3u4L0LaCBENMca0T0p9GQkBs3RN7xYEVWyh0/yf3aiIsvakyaE6igbkInnIAoMLOxTVXtRFh+BOk2q37P7hUIbwezKgKFt1X8k9eS4AYwJUMMlc5J3aNhoorNveZ93Ujr6h3SI5fbqNxT0iQhjzJEcHgdc3+4UWYJIsX/7FbPu9zu3BnA7DrZSHiDVUtpFxoMLQ65nbaAFnhWGZpU6qsxoCpRc2jN+JukMeoeDAvpZGh50xysRjnmZ2dpLohryfthXqqnPoJjvKVJDTu7MKv7PjS2Tq2xLn3MJecQ2mYDeQJazi1ByiODKVZXZD/2KXyi0zEh29u8TnWLugsFRCTF3MQhtJKX9YysyygB9F0kBOmoMx58uQQVkkoTD849iNDs3cObs7eMCwI/Wbm3Bft9x6iHAVP5PNHHdi7TixPoW0Tgo74ffXlhYzZ4YOx1VeZwo=
