language: node_js
install:
  - npm install codecov -g
  - npm ci
script:
  - npm test
after_success:
  - codecov
node_js:
  - lts/*
branches:
  only:
    - master
notifications:
  slack:
    if: type = pull_request
    secure: kRG90ZNNzlzwuRpuTpNjQ201h9V76PMSqj8oOgQmJ73gf7X46tw6iS1hkMdQ7PUMmnyT5H+x+zh4p2TkKs6/8nDLkcrCWuWCwxPmxdgjcUA1oVUCWTaOHe+QMJnoWMQI31L/XV57+6YqUR8xDF1T3Yo6hH1LeqF/uXLtFhgpKDLxMlZY5A0iwRXVGJSElr3t+pzq+o5Cf90W6UdX4ftBSaiPwMaqrC/Rb8KiTV5IwXPVqoUO3yb8+il3eGgS2vqXXNP6D1OSw6b3xdr+pLF/i9fnm684FNNFEuIj2pl+GDCMH9vQzSpgzdY2YRuREqN5hadNRUmCAX0mZ+TclY+ZGoT0BU4H3ZyggNZv6l9N3/jRWYoBiMOnLvVPSbPkI25R+LVmYIgMnhHYBgTpUNvtZqz0Y0yfUJBw8ua77v68YkIQs4FOgDgDoSKmAC6eHp/PKw/prRSJixx3VnH4F1bhaTh13VcAXKKXmSxwATUlL05QyH3Znsaw43R3kFkkc7bJIjru4potr+aQd4su2+3xNs0U9pe3J/hsHbFJ3ImYWrUaDvkV3j2Tb4meOJoxl9rrzIVFPe2SLC2PpLa2HO6UibjKCTQYR7A5aydgg4vctzhwc8RvBhZ9nLwfNZ5xv1UYRfrjjhPIiYVy+6pjfG4+KBzDlrVbSdSMvMU9LXmrb5A=
