language: node_js
install:
  - npm install codecov -g
  - npm ci
script:
  - npm test
after_success:
  - codecov
node_js:
  - lts/*
  - 13.13.0
notifications:
  slack:
    if: type = pull_request
    rooms:
      - secure: BXBqtph+T1DSzFsONrZSK3ke61xGlgVOFx6R4TpOXAJ+pqP3qT0M3+WnrBZGA6or0VGIo/+k96mlfugFEff89q8lP5DZrIz2sKEkPjLjns01yTOHfArW+QnFig9aUeAVPdvOXh+WnJEIC7aSD/+VhnbfVb5eN2CdJVBfw/Eldmwf2fsG5W5sKgCGmXDINi9AkVMlgxuD7xrFPnzUNfg7jekDbR3XT23nX6HVtOfal+XuHmmgc2vdklvCLZEpDZXbhdNPP2Os7wUWrlXictTbGlivIro1y5ht2K7nERbr+/wapSXq8r8wU44CVpVI+B4vgR1yHEQle0rucsNTo4BQL9V5tWilpNnxGwOqLMAs/FbZjICgM0cpyVL88ljmotE9Doo4YppK99pozQu0tedyJv4WSeLS+Fq1pAgC+MM+n3213bZU2kLz6MqCieh/iikl9+v+AoqdZ8Hbvf3osE9jkvQhPvVGie7dorTtOJ6EJZExUARKNTyf/EMKUqQWQ/oNBp4A+YqrUkrPdn1XuY+aBlipPugX5DR/SFYoX+sGYbKei1ZoMMgicHU4VcbZ71iZ5+HMlhAz9OWnOEwRG7XgoWIGghJ3AbeTm3zKdEdTakpyQ/KQ+MoaIFNr8U0MJ7XohUm6pduvpO71cPuVUQfmpDcvcu3UWzkoXonxOkwg3Gs=
    on_success: always
    on_failure: always
