language: node_js
install:
  - npm install codecov -g
  - npm ci
script:
  - npm test
after_success:
  - codecov
node_js:
  - lts/*
branches:
  only:
    - master
notifications:
  slack:
    if: type IN (pull_request) AND branch = master
    secure: PWwqr4T3tIimMrEniKIhkpAZJKcaorT/r+RHxBJJfqgj5Jq1AmO/dSNHZrVdsQFz8qKSdeR884hhsf5PSnEpjOTdd7F9FbEfu28wHolyyr0hYGYliD5isN6H4kmzkcVWvq8zOsxxRIW2uJSj8XPUHbs18vy43uyfiXoNuRtYlLTMEbQIvS7sztqIK6l6v6xKP0L2ccEvZGUPOVviQOJrsjKFWN9du22yxHu0vh1WAbZGJYHkNMeIdkAZ3rB5wg+z1mwki18ACy7LOz9isIt4CxbrPrZtGAUFBLX7wQzyOO5dXx/6sWJwlrAge55mGqIcTBOVhlecMyrldZMCjK++eDQPU1GReyaeLV3JsVbH5Z+NyojgXWx1FkNIRLrTGRs+P0whVIFzyeXmvjFyrjBJdacZUMM9FMwDhzdwT2OE6WYet0JDsUrwHF66aFWjtSN9mqvd4NChD+ABnx4wcCByp21QdHM73c76qkPylBZnCo3WchHF8UNPWk7BqQ+zWBuYZhqACYeelIvlZkmu756Z08KBNggbDST8ihAETaycaytZXgfORLMnfaWV770P6aUjMFeJQZBgnVnpl8sU+gv/K2BnZujMFLObTh7mi7VrMhl7kiTsZLIYAD+WYw6Ykb0ce4LddhoA5CObIuGYKQkYYIBb0NF2XufZGEzaBIDp2Ik=
