export enum ConversationContentTypes {
    INFO = 'info',
    SDES = 'sdes',
    UNAUTH_SDES = 'unAuthSdes',
    CAMPAIGN = 'campaign',
    MESSAGE_RECORDS = 'messageRecords',
    AGENT_PARTICIPANTS = 'agentParticipants',
    AGENT_PARTICIPANTS_ACTIVE = 'agentParticipantsActive',
    CONSUMER_PARTICIPANTS = 'consumerParticipants',
    TRANSFERS = 'transfers',
    INTERACTIONS = 'interactions',
    MESSAGE_SCORES = 'messageScores',
    MESSAGE_STATUSES = 'messageStatuses',
    SKILL_CHANGES = 'skillChanges',
    CONVERSATION_SURVEYS = 'conversationSurveys',
}
